---
- name: rpmfusion enabled (https://rpmfusion.org/Configuration)
  hosts: all
  become: yes
  tasks:
    - name: rpmfusion repo added
      include_tasks: rpmfusion_tasks.yml
      loop:
        - free
        - nonfree

- name: system initialized
  hosts: all
  become: yes
  gather_facts: no
  vars_files: [vars.yml]
  tasks:
    # - name: system up to date
    #   dnf: name=* state=latest update_cache=yes
    - name: unwanted packages removed
      dnf:
        name: fedora-chromium-config
        state: absent
    - name: packages installed
      dnf:
        name: "{{ packages }}"
        state: present
    - name: rpmfusion packages installed
      dnf:
        name: "{{ rpmfusion_packages }}"
        state: present
    - name: user created
      user:
        name: "{{ username }}"
        state: present
        shell: /usr/bin/fish
        generate_ssh_key: yes
        groups: wheel
    - name: unnecessary services disabled
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - packagekit
        - raid-check.timer

- name: tailscale configured
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: tailscale repo added
      get_url: 
        url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo
    - name: tailscale installed
      dnf:
        name: tailscale
        state: present
    - name: tailscale service enabled
      service:
        name: tailscaled
        state: started
        enabled: yes

- name: NUT configured
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: NUT config directory exists
      file:
        path: /etc/nut
        state: directory
    - name: UPS configuration placed
      copy:
        src: ups.conf
        dest: /etc/nut/ups.conf

# - name: plex installed
#   hosts: all
#   become: yes
#   gather_facts: no
#   tasks:
#     - name: plex repo added
#       copy:
#         dest: /etc/yum.repos.d/plex.repo
#         content: |
#           [Plexrepo]
#           name=plexrepo
#           baseurl=https://downloads.plex.tv/repo/rpm/$basearch/
#           enabled=1
#           gpgkey=https://downloads.plex.tv/plex-keys/PlexSign.key
#           gpgcheck=1
#     - name: plex package installed
#       dnf:
#         name: plexmediaserver
#         update_cache: yes

# - name: github CLI installed
#   hosts: all
#   become: yes
#   gather_facts: no
#   tasks:
#     # TODO fix once feature added for dnf module: https://github.com/ansible/ansible/issues/46963
#     - name: gh repo installed
#       command:
#         cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
#         warn: false
#       args:
#         creates: /etc/yum.repos.d/gh-cli.repo
#     - name: gh package installed
#       dnf:
#         state: present
#         name: gh

- name: /home initialized
  hosts: all
  become: yes
  become_user: "{{ username }}"
  gather_facts: no
  vars_files: [vars.yml]
  tasks:
    - name: home directories exist
      file:
        path: /home/{{ username }}/{{ item }}
        state: directory
      loop: "{{ home_directories }}"

- name: dotfiles symlinked
  hosts: all
  become: yes
  become_user: "{{ username }}"
  gather_facts: no
  vars_files: [vars.yml]
  roles:
    - geerlingguy.dotfiles
