---
- name: rpmfusion enabled (https://rpmfusion.org/Configuration)
  tags: [rpmfusion, always]
  hosts: all
  become: yes
  tasks:
    - name: repo added
      include_tasks: rpmfusion_tasks.yml
      loop:
        - free
        - nonfree

- name: system initialized
  hosts: all
  become: yes
  gather_facts: no
  vars_files: [vars.yml]
  tasks:
    - name: system up to date
      tags: [update, never]
      dnf: name=* state=latest update_cache=yes
    - name: packages installed
      dnf:
        name: "{{ packages }}"
        state: present
    - name: rpmfusion packages installed
      tags: [rpmfusion, always]
      dnf:
        name: "{{ rpmfusion_packages }}"
        state: present
    - name: lf installed
      unarchive:
        src: "https://github.com/gokcehan/lf/releases/download/{{ lf_version }}/lf-{{ lf_arch }}.tar.gz"
        dest: /usr/bin
        remote_src: yes
        mode: 0755
    # - name: user created
    #   user:
    #     name: "{{ username }}"
    #     state: present
    #     shell: /usr/bin/fish
    #     generate_ssh_key: yes
    #     groups: wheel

- name: 1password installed (https://support.1password.com/getting-started-linux/)
  hosts: all
  become: yes
  gather_facts: no
  tags: [1password, never]
  tasks:
    - name: key imported
      rpm_key:
        state: present
        key: https://downloads.1password.com/linux/keys/1password.asc
    - name: repo added
      copy:
        dest: /etc/yum.repos.d/1password.repo
        content: |
          [1password]
          name=1Password
          baseurl=https://downloads.1password.com/linux/rpm
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://downloads.1password.com/linux/keys/1password.asc
    - name: package installed
      dnf:
        name: 1password
        state: present
        update_cache: yes

- name: /home initialized
  hosts: all
  tags: [home, always]
  become: yes
  become_user: "{{ username }}"
  gather_facts: no
  vars_files: [vars.yml]
  tasks:
    - name: home directories exist
      file:
        path: /home/{{ username }}/{{ item }}
        state: directory
      loop: "{{ home_directories }}"
    - name: bitwarden cli installed
      tags: [bitwarden, never]
      unarchive:
        src: https://vault.bitwarden.com/download/?app=cli&platform=linux
        dest: /home/{{ username }}/bin
        remote_src: yes
        mode: +x

- name: dotfiles symlinked
  hosts: all
  become: yes
  become_user: "{{ username }}"
  gather_facts: no
  tags: [dotfiles, never]
  vars_files: [vars.yml]
  roles:
    - geerlingguy.dotfiles
